export const backgroundData = [
  {
    backgroundColor: "#FFFFFF",
    borderColor: "#F0F2F5",
    textColor: "#0B404D",
    fontSize: "20px",
    fontWeight: "400",
    textAlign: "left",
    height: "120px",
  },
  {
    backgroundColor: "#25D4FF",
    borderColor: "#F1F1F1",
    textColor: "#0B404D",
    fontSize: "25px",
    fontWeight: "500",
    textAlign: "left",
    height: "210px",
  },
  {
    backgroundColor: "#F35369",
    borderColor: "#F1F1F1",
    textColor: "#FBCBD2",
    fontSize: "25px",
    fontWeight: "500",
    textAlign: "left",
    height: "210px",
  },
  {
    backgroundColor: "#E9B73A",
    borderColor: "#F1F1F1",
    textColor: "#493A13",
    fontSize: "25px",
    fontWeight: "500",
    textAlign: "left",
    height: "210px",
  },
  {
    backgroundColor: "green",
    borderColor: "#F1F1F1",
    textColor: "limegreen",
    fontSize: "25px",
    fontWeight: "500",
    textAlign: "center",
    height: "210px",
  },
  {
    backgroundColor: "red",
    borderColor: "#F1F1F1",
    textColor: "white",
    fontSize: "25px",
    fontWeight: "500",
    textAlign: "center",
    height: "210px",
  },
];
